# http://code.google.com/appengine/docs/python/config/appconfig.html

application: scdsitemon
version: 4
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /cron
  script: main.py
  login: admin
- url: /clear
  script: main.py
  login: admin
- url: /admin
  script: main.py
  login: admin
- url: /checkurl
  script: main.py
- url: /exectask
  script: main.py
- url: /images
  static_dir: images
- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon\.ico
- url: /
  script: main.py
- url: /.*
  script: main.py
  login: required

libraries:
- name: django
  version: "1.2"
- name: webapp2
  version: "2.5.2"

inbound_services:
- xmpp_message

builtins:
# - datastore_admin: on
